const { contextBridge, ipcRenderer } = require('electron');

const inv = (ch, ...a) => ipcRenderer.invoke(ch, ...a);

contextBridge.exposeInMainWorld('api', {
  db: {
    exportFile: ()          => inv('db:exportFile'),
    pickImportFile: ()      => inv('db:pickImportFile'),
    importMergeFile: (p,targetNexusId)       => inv('db:importMergeFile', p,targetNexusId),
    exportNexusFile: (nexusId,name)          => inv('db:exportNexusFile', nexusId,name),
    importNexusFile: (nexusId)               => inv('db:importNexusFile', nexusId),
    exportModuleFile: (nexusId,modId,name)   => inv('db:exportModuleFile', nexusId,modId,name),
    importModuleFile: (nexusId,parentId)     => inv('db:importModuleFile', nexusId,parentId),
    importModuleFileAt: (nexusId,parentId,filePath) => inv('db:importModuleFileAt', nexusId,parentId,filePath),
  },
  nexus: {
    getAll:  ()            => inv('nexus:getAll'),
    get:     (id)          => inv('nexus:get', id),
    create:  (n,m,c,fp)    => inv('nexus:create', n,m,c,fp),
    update:  (id,n,m,c)    => inv('nexus:update', id,n,m,c),
    delete:  (id)          => inv('nexus:delete', id),
    defaultPath:  (name)   => inv('nexus:defaultPath', name),
    pickLocation: (name)   => inv('nexus:pickLocation', name),
    relink:       (id)     => inv('nexus:relink', id),
    duplicate:    (id)     => inv('nexus:duplicate', id),
    exportFile:   (id)     => inv('nexus:exportFile', id),
    shareFile:    (id)     => inv('nexus:shareFile', id),
    revealFile:   (id)     => inv('nexus:revealFile', id),
  },
  shell: {
    revealPath:  (p)       => inv('shell:revealPath', p),
    composeMail: (s2,b)    => inv('shell:composeMail', s2,b),
  },
  note: {
    getFolders:    (nx)           => inv('note:getFolders', nx),
    createFolder:  (nx,n,p,c)     => inv('note:createFolder', nx,n,p,c),
    updateFolder:  (id,n,p,c)     => inv('note:updateFolder', id,n,p,c),
    deleteFolder:  (id)           => inv('note:deleteFolder', id),
    getAll:        (nx)           => inv('note:getAll', nx),
    get:           (id)           => inv('note:get', id),
    create:        (nx,t,f,c)     => inv('note:create', nx,t,f,c),
    update:        (id,t,f,c,p)   => inv('note:update', id,t,f,c,p),
    updateContent: (id,content)   => inv('note:updateContent', id,content),
    delete:        (id)           => inv('note:delete', id),
  },
  module: {
    getTree: (nx)          => inv('module:getTree', nx),
    getNestItems: (nx)     => inv('module:getNestItems', nx),
    get:     (id)          => inv('module:get', id),
    create:  (data)        => inv('module:create', data),
    update:  (id,data)     => inv('module:update', id,data),
    updateDescription: (id,d) => inv('module:updateDescription', id,d),
    delete:  (id)          => inv('module:delete', id),
    duplicate: (id)        => inv('module:duplicate', id),
    move:    (nx,id,parentId,ids) => inv('module:move', nx,id,parentId,ids),
    count:   (nx)          => inv('module:count', nx),
    getAttrs:   (id)          => inv('module:getAttrs', id),
    upsertAttr: (id,aid,n,v)  => inv('module:upsertAttr', id,aid,n,v),
    deleteAttr: (id)          => inv('module:deleteAttr', id),
    getUi:   (id)          => inv('module:getUi', id),
    setUi:   (id,k,v)      => inv('module:setUi', id,k,v),
    getTags: (id)          => inv('module:getTags', id),
    setTags: (id,tags)     => inv('module:setTags', id,tags),
    getLinks: (id)         => inv('module:getLinks', id),
    getInspector: (id)     => inv('module:getInspector', id),
    getChildStats:   (pid)   => inv('module:getChildStats', pid),
  },
  history: {
    undo: ()               => inv('history:undo'),
    redo: ()               => inv('history:redo'),
  },
  classifier: {
    setCatType:        (id,ct)             => inv('classifier:setCatType', id,ct),
    getObjects:        (mref)              => inv('classifier:getObjects', mref),
    getObjectsFull:    (mref)              => inv('classifier:getObjectsFull', mref),
    getObject:         (id)                => inv('classifier:getObject', id),
    createObject:      (mref,n,c,ic)          => inv('classifier:createObject', mref,n,c,ic),
    updateObject:      (id,n,c,ic)            => inv('classifier:updateObject', id,n,c,ic),
    updateObjectNote:  (id,note)              => inv('classifier:updateObjectNote', id,note),
    deleteObject:      (id)                   => inv('classifier:deleteObject', id),
    getTemplates:      (mref)                 => inv('classifier:getTemplates', mref),
    getObjectTemplates:(mref,oref)            => inv('classifier:getObjectTemplates', mref,oref),
    createTemplate:    (mref,d,t,lv,c,oref,ls)=> inv('classifier:createTemplate', mref,d,t,lv,c,oref,ls),
    updateTemplate:    (id,d,t,lv,c,ls)       => inv('classifier:updateTemplate', id,d,t,lv,c,ls),
    deleteTemplate:    (id)                   => inv('classifier:deleteTemplate', id),
    countObjectTemplates: (oref)              => inv('classifier:countObjectTemplates', oref),
    getAttrs:          (oid)                  => inv('classifier:getAttrs', oid),
    upsertAttr:        (oid,tid,v)            => inv('classifier:upsertAttr', oid,tid,v),
    upsertAttrCondition: (oid,tid,v)          => inv('classifier:upsertAttrCondition', oid,tid,v),
    getLevels:         (oid)                  => inv('classifier:getLevels', oid),
    createLevel:       (oid,tid)              => inv('classifier:createLevel', oid,tid),
    updateLevelField:  (id,f,v)               => inv('classifier:updateLevelField', id,f,v),
    deleteLevel:       (id)                   => inv('classifier:deleteLevel', id),
    moveLevels:        (oid,tid,ids)          => inv('classifier:moveLevels', oid,tid,ids),
  },
  wanderer: {
    list:   (mref)                  => inv('wanderer:list', mref),
    create: (mref,ev,key,px,py,ar)  => inv('wanderer:create', mref,ev,key,px,py,ar),
    update: (id,ev,key,px,py,ar)    => inv('wanderer:update', id,ev,key,px,py,ar),
    delete: (id)                    => inv('wanderer:delete', id),
  },
  narrator: {
    getDialogues:      (mref)           => inv('narrator:getDialogues', mref),
    createDialogue:    (mref,n,c,px,py) => inv('narrator:createDialogue', mref,n,c,px,py),
    updateDialogue:    (id,n,c)         => inv('narrator:updateDialogue', id,n,c),
    updateDialogueDescription: (id,desc) => inv('narrator:updateDialogueDescription', id,desc),
    updateDialoguePos: (id,px,py)       => inv('narrator:updateDialoguePos', id,px,py),
    deleteDialogue:    (id)             => inv('narrator:deleteDialogue', id),
    getEdges:          (mref)           => inv('narrator:getEdges', mref),
    createEdge:        (mref,f,to,lb)   => inv('narrator:createEdge', mref,f,to,lb),
    updateEdgeLabel:   (id,lb)          => inv('narrator:updateEdgeLabel', id,lb),
    deleteEdge:        (id)             => inv('narrator:deleteEdge', id),
    getTalks:          (did)            => inv('narrator:getTalks', did),
    createTalk:        (did,sp,tx,lk,ty) => inv('narrator:createTalk', did,sp,tx,lk,ty),
    updateTalk:        (id,sp,tx,lk)    => inv('narrator:updateTalk', id,sp,tx,lk),
    deleteTalk:        (id)             => inv('narrator:deleteTalk', id),
    moveTalks:         (did,ids)        => inv('narrator:moveTalks', did,ids),
    getChoiceOptions:  (did)            => inv('narrator:getChoiceOptions', did),
    createChoiceOption:(tid,tx)         => inv('narrator:createChoiceOption', tid,tx),
    updateChoiceOption:(id,tx,k,ef,j)   => inv('narrator:updateChoiceOption', id,tx,k,ef,j),
    deleteChoiceOption:(id)             => inv('narrator:deleteChoiceOption', id),
  },
  author: {
    getChapters:   (mref)    => inv('author:getChapters', mref),
    createChapter: (mref,n)  => inv('author:createChapter', mref,n),
    renameChapter: (id,n)    => inv('author:renameChapter', id,n),
    updateContent: (id,c)    => inv('author:updateContent', id,c),
    deleteChapter: (id)      => inv('author:deleteChapter', id),
    setChapterLabel: (id,lb) => inv('author:setChapterLabel', id,lb),
    moveChapter:   (mref,ids) => inv('author:moveChapter', mref,ids),
    exportDoc:     (n,html)  => inv('author:exportDoc', n,html),
  },
  drafter: {
    exportFile: (n,ext,c) => inv('drafter:exportFile', n,ext,c),
  },
  chatscribe: {
    getSessions:   (mref)    => inv('chatscribe:getSessions', mref),
    createSession: (mref,n)  => inv('chatscribe:createSession', mref,n),
    renameSession: (id,n)    => inv('chatscribe:renameSession', id,n),
    deleteSession: (id)      => inv('chatscribe:deleteSession', id),
    getMessages:   (sref)    => inv('chatscribe:getMessages', sref),
    createMessage: (sref,t)  => inv('chatscribe:createMessage', sref,t),
    updateMessage: (id,t)    => inv('chatscribe:updateMessage', id,t),
    deleteMessage: (id)      => inv('chatscribe:deleteMessage', id),
    updateMessageStyle: (id,c,s) => inv('chatscribe:updateMessageStyle', id,c,s),
  },
  calendar: {
    listTemplates:  (nx)        => inv('calendar:listTemplates', nx),
    saveTemplate:   (nx,n,spec) => inv('calendar:saveTemplate', nx,n,spec),
    deleteTemplate: (id)        => inv('calendar:deleteTemplate', id),
    ensureBuiltin:  (nx,n,spec) => inv('calendar:ensureBuiltin', nx,n,spec),
  },
  viewer: {
    index:          (nx)        => inv('viewer:index', nx),
    getRelations:   (nx)        => inv('viewer:getRelations', nx),
    createRelation: (nx,f,tk,l,c) => inv('viewer:createRelation', nx,f,tk,l,c),
    updateRelation: (id,l,c)      => inv('viewer:updateRelation', id,l,c),
    deleteRelation: (id)        => inv('viewer:deleteRelation', id),
  },
  sketcher: {
    getPages:     (mref)         => inv('sketcher:getPages', mref),
    createPage:   (mref,n)       => inv('sketcher:createPage', mref,n),
    renamePage:   (id,n)         => inv('sketcher:renamePage', id,n),
    movePage:     (id,dir)       => inv('sketcher:movePage', id,dir),
    deletePage:   (id)           => inv('sketcher:deletePage', id),
    getStrokes:   (pref)         => inv('sketcher:getStrokes', pref),
    addStroke:    (pref,c,w,pts) => inv('sketcher:addStroke', pref,c,w,pts),
    deleteStroke: (id)           => inv('sketcher:deleteStroke', id),
    getPins:      (pref)         => inv('sketcher:getPins', pref),
    addPin:       (pref,k,px,py) => inv('sketcher:addPin', pref,k,px,py),
    movePin:      (id,px,py)     => inv('sketcher:movePin', id,px,py),
    deletePin:    (id)           => inv('sketcher:deletePin', id),
    exportPng:    (n,dataUrl)    => inv('sketcher:exportPng', n,dataUrl),
  },
  migrate: {
    list: (target,nx)         => inv('migrate:list', target,nx),
    run:  (nx,target,id,ctx)  => inv('migrate:run', nx,target,id,ctx),
    preview:       (nx) => inv('migrate:preview', nx),
    getPromptSeen: (nx) => inv('migrate:getPromptSeen', nx),
    setPromptSeen: (nx) => inv('migrate:setPromptSeen', nx),
  },
  versions: {
    list:    (mref) => inv('versions:list', mref),
    restore: (id)   => inv('versions:restore', id),
  },
  setting: {
    get: (k)   => inv('setting:get', k),
    set: (k,v) => inv('setting:set', k,v),
  },
  sync: {
    getConfig:    ()           => inv('sync:getConfig'),
    setConfig:    (u,k)        => inv('sync:setConfig', u,k),
    googleLogin:  (u,t)        => inv('sync:googleLogin', u,t),
    googleLogout: ()           => inv('sync:googleLogout'),
    authStatus:   ()           => inv('sync:authStatus'),
    status:       (nx)         => inv('sync:status', nx),
    push:         (nx,pw)      => inv('sync:push', nx,pw),
    pull:         (nx,vaultId) => inv('sync:pull', nx,vaultId),
    pullByToken:  (nx,tok,pw)  => inv('sync:pullByToken', nx,tok,pw),
    deleteUpload: (vaultId)    => inv('sync:deleteUpload', vaultId),
  },
  supabase: {
    getSetup:   ()          => inv('supabase:getSetup'),
    setSetup:   (u,k)       => inv('supabase:setSetup', u,k),
    clearSetup: ()          => inv('supabase:clearSetup'),
    getSql:     ()          => inv('supabase:getSql'),
    check:      (u,k)       => inv('supabase:check', u,k),
    install:    (tok,u,k)   => inv('supabase:install', tok,u,k),
    openDash:   (page)      => inv('supabase:openDash', page),
  },
  drive: {
    getConfig:       ()      => inv('drive:getConfig'),
    setConfig:       (i,s)   => inv('drive:setConfig', i,s),
    connect:         ()      => inv('drive:connect'),
    disconnect:      ()      => inv('drive:disconnect'),
    status:          ()      => inv('drive:status'),
    setAutoBackup:   (en)    => inv('drive:setAutoBackup', en),
    setBackupLayout: (en)    => inv('drive:setBackupLayout', en),
    setBackupDdx:    (en)    => inv('drive:setBackupDdx', en),
    backupNow:       (lyt)   => inv('drive:backupNow', lyt),
    restoreLayout:   ()      => inv('drive:restoreLayout'),
    restoreDatabase: ()      => inv('drive:restoreDatabase'),
    getBackupLog:    ()      => inv('drive:getBackupLog'),
    listLayoutSlots:   ()          => inv('drive:listLayoutSlots'),
    saveLayoutSlot:    (name,json) => inv('drive:saveLayoutSlot', name,json),
    restoreLayoutSlot: (id)        => inv('drive:restoreLayoutSlot', id),
    deleteLayoutSlot:  (id)        => inv('drive:deleteLayoutSlot', id),
  },
  cloud: {
    listProviders: ()       => inv('cloud:listProviders'),
    setActive:     (id)     => inv('cloud:setActive', id),
    setPrefs:      (id,p)   => inv('cloud:setPrefs', id,p),
    getConfig:     (id)     => inv('cloud:getConfig', id),
    setConfig:     (id,cfg) => inv('cloud:setConfig', id,cfg),
    connect:       (id)     => inv('cloud:connect', id),
    disconnect:    (id)     => inv('cloud:disconnect', id),
    status:        (id)     => inv('cloud:status', id),
  },
  update: {
    check:        ()    => inv('update:check'),
    dismiss:      (v)   => inv('update:dismiss', v),
    openDownload: (url) => inv('update:openDownload', url),
    getAutoCheck: ()    => inv('update:getAutoCheck'),
    setAutoCheck: (v)   => inv('update:setAutoCheck', v),
  },
  plugin: {
    list:      ()    => inv('plugin:list'),
    listOrgRepos: () => inv('plugin:listOrgRepos'),
    preview:   (url) => inv('plugin:preview', url),
    install:   (url) => inv('plugin:install', url),
    installDependency: (id, url) => inv('plugin:installDependency', id, url),
    uninstall: (id)  => inv('plugin:uninstall', id),
    launch:    (id)  => inv('plugin:launch', id),
    stop:      (id)  => inv('plugin:stop', id),
    isRunning: (id)  => inv('plugin:isRunning', id),
  },
  importdock: {
    list:          (nx)     => inv('importdock:list', nx),
    add:           (nx,fs2) => inv('importdock:add', nx,fs2),
    setLinker:     (id,k)   => inv('importdock:setLinker', id,k),
    setUseAsImage: (id,on)  => inv('importdock:setUseAsImage', id,on),
    delete:        (id)     => inv('importdock:delete', id),
    displayImages: (nx)     => inv('importdock:displayImages', nx),
    pickFolder:    ()       => inv('importdock:pickFolder'),
    readFile:      (id)     => inv('importdock:readFile', id),
    readFiles:     (ids)    => inv('importdock:readFiles', ids),
  },
  sagehut: {
    stats:      (nx) => inv('sagehut:stats', nx),
    linkerList: (nx) => inv('sagehut:linkerList', nx),
  },
  designer: {
    getNodes:   (mref)              => inv('designer:getNodes', mref),
    createNode: (mref,s,px,py,tx,c,k) => inv('designer:createNode', mref,s,px,py,tx,c,k),
    updateNode: (id,s,tx,c)         => inv('designer:updateNode', id,s,tx,c),
    moveNode:   (id,px,py)          => inv('designer:moveNode', id,px,py),
    deleteNode: (id)                => inv('designer:deleteNode', id),
    getEdges:   (mref)              => inv('designer:getEdges', mref),
    createEdge: (mref,f,tk,l)       => inv('designer:createEdge', mref,f,tk,l),
    updateEdge: (id,l)              => inv('designer:updateEdge', id,l),
    deleteEdge: (id)                => inv('designer:deleteEdge', id),
  },
  wiki: {
    resolve:    (name,nx)  => inv('wiki:resolve', name,nx),
    backlinks:  (key)      => inv('wiki:backlinks', key),
    outgoing:   (key)      => inv('wiki:outgoing', key),
    quickIndex: (nx)       => inv('wiki:quickIndex', nx),
    entityPath: (key)      => inv('wiki:entityPath', key),
    rebuild:    ()         => inv('wiki:rebuild'),
    resolveKeys: (keys)    => inv('wiki:resolveKeys', keys),
    linkCounts:  (nx)      => inv('wiki:linkCounts', nx),
    getGraph:   (nx)       => inv('wiki:getGraph', nx),
    renameTarget: (key,o,n) => inv('wiki:renameTarget', key,o,n),
  },
  timeline: {
    getAll:  (pid)        => inv('timeline:getAll', pid),
    create:  (pid,n,c)    => inv('timeline:create', pid,n,c),
    getModuleTimelines: (moduleRef) => inv('timeline:getModuleTimelines', moduleRef),
    createModuleTimeline: (moduleRef,n,c) => inv('timeline:createModuleTimeline', moduleRef,n,c),
    update:  (id,n,c)     => inv('timeline:update', id,n,c),
    delete:  (id)         => inv('timeline:delete', id),
    getOrCreateDate: (d,m,y,hh,mm) => inv('timeline:getOrCreateDate', d,m,y,hh,mm),
    getEvents: (tlid)     => inv('timeline:getEvents', tlid),
    createEvent: (tlid,n,s,e,c,story) => inv('timeline:createEvent', tlid,n,s,e,c,story),
    updateEvent: (id,n,s,e,c,story)  => inv('timeline:updateEvent', id,n,s,e,c,story),
    updateEventStory: (id,story) => inv('timeline:updateEventStory', id,story),
    updateEventIcon: (id,icon,color) => inv('timeline:updateEventIcon', id,icon,color),
    deleteEvent: (id)     => inv('timeline:deleteEvent', id),
    getEventTags: (eid)   => inv('timeline:getEventTags', eid),
    setEventTags: (eid,tags) => inv('timeline:setEventTags', eid,tags),
    addEventTag: (eid,tid) => inv('timeline:addEventTag', eid,tid),
    removeEventTag: (eid,tid) => inv('timeline:removeEventTag', eid,tid),
  },
  map: {
    getAll: (pid)            => inv('map:getAll', pid),
    create: (pid,n,c)        => inv('map:create', pid,n,c),
    update: (id,n,c)         => inv('map:update', id,n,c),
    delete: (id)             => inv('map:delete', id),
    getAreas: (mid)          => inv('map:getAreas', mid),
    createArea: (mid,n,c)    => inv('map:createArea', mid,n,c),
    updateArea: (id,n,c)     => inv('map:updateArea', id,n,c),
    deleteArea: (id)         => inv('map:deleteArea', id),
    getPoints: (aid)         => inv('map:getPoints', aid),
    setPoints: (aid,points)  => inv('map:setPoints', aid, points),
    getModuleMap: (mref)        => inv('map:getModuleMap', mref),
    getOrCreateModuleMap: (mref) => inv('map:getOrCreateModuleMap', mref),
  },
  hashtag: {
    getAll:  ()           => inv('hashtag:getAll'),
    create:  (n,c)        => inv('hashtag:create', n,c),
    update:  (id,n,c)     => inv('hashtag:update', id,n,c),
    delete:  (id)         => inv('hashtag:delete', id),
    getObjectsByTag: (tagId, projectId) => inv('hashtag:getObjectsByTag', tagId, projectId),
    getEventsByTag: (tagId, projectId)  => inv('hashtag:getEventsByTag', tagId, projectId),
  },
  color: {
    getAll:  ()            => inv('color:getAll'),
    add:     (code)        => inv('color:add', code),
    markUsed:(id)          => inv('color:markUsed', id),
    getRecent:()           => inv('color:getRecent'),
    delete:  (id)          => inv('color:delete', id),
    getSymbolCollection: () => inv('color:getSymbolCollection'),
  },
  window: {
    minimize:       () => inv('window:minimize'),
    toggleMaximize: () => inv('window:toggleMaximize'),
    close:          () => inv('window:close'),
    openNexus:      (nexusId) => inv('window:openNexus', nexusId),
    openWelcome:    () => inv('window:openWelcome'),
    openNexusReplace: (nexusId) => inv('window:openNexusReplace', nexusId),
    openBuilderTab: (nexusId, tabKey) => inv('window:openBuilderTab', nexusId, tabKey),
    getId:          () => inv('window:getId'),
    moveTabToMain:  (nexusId, tabKey) => inv('window:moveTabToMain', nexusId, tabKey),
    onTabInbound:   (cb) => ipcRenderer.on('builder:tabInbound', (_, nexusId, tabKey) => cb(nexusId, tabKey)),
  },
});
